module Model
  module CombatResult
    WINANDWINGAME = :WINANDWINGAME
    WIN = :WIN
    LOSE = :LOSE
    LOSEANDESCAPE = :LOSEANDESCAPE
    LOSEANDDIE = :LOSEANDDIE
    LOSEANDCONVERT = :LOSEANDCONVERT
  end
end